image: maven:4.0.0-openjdk-17

stages:
  - build
  - test

compilation :
  stage : build
  script :
    - echo 'build'
    - mvn compile
  
tests : 
  stage : test
  script :
    -echo 'test'
    -mvn test