image: maven:4.0.0-openjdk-17

stages:
  - build
  - test

compilation :
  stage : build
  script :
    - apt-get update
    - echo 'update fait'
    

tests : 
  stage : test
  script :
    -echo 'faut faire les ci-cd tests'